site_name: WING - btw2201-Databases
site_url: https://tjaeggi.github.io/btw2201_databases/
theme:
  name: material
  font:
    #text: Roboto
    #text: Open Sans
    text: Noto Sans
    #code: Red Hat Mono
    code: Noto Mono
    #code: Ubuntu Mono
  logo:  assets/Micropython-logo.svg.png
  favicon: assets/Micropython-logo.svg.png
  #icon:
  #  logo: fontawesome/solid/face-smile-beam
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: deep orange
  features:
    - navigation.footer
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate

plugins:
  - glightbox
  - search

extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/thomas-j%C3%A4ggi-026350141/

copyright: Copyright &copy; 2024 Thomas Jäggi

markdown_extensions:
  - attr_list
  - tables
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  spick/installationsjournal.md
  spick/spick_markdown.md

nav:
  - 'ABOUT THIS WEBSITE': index.md
  - 'LE01-CSVs mit Python': 
      - 'UE01-1-Aufgaben': le01/ue01-1.md
      - 'UE01-1-Lösungsvorschläge': le01/Loesungsvorschlaege_ue01-1.md
  - 'LE02-SELECT Abfragen': 
      - 'UE02-1-Aufgaben': le02/UE02-1.md
      - 'UE02-1-Lösungsvorschläge': le02/Loesungsvorschlaege_UE02-1.md
      - 'UE02-2-Aufgaben und Lösungen': le02/UE02-2.md
  - 'LE03-Weiterführende SELECTs':
      - 'UE03-1-AB-Ranking Table und View': le03/UE03-01-AB.md
      - 'UE03-2-Datum und Zeit': le03/UE03-2.md
      - 'UE03-3-CSV in SQLite': le03/UE03-3.md
      - 'UE03-4-SQL-Abfragen Strasserverz.': le03/UE03-4.md
  - 'LE04-SQL und Python':
      - 'Einführung Python mit SQLite': le04/le04-einfpythonsqlite.md
      - 'Einführung Bindings': le04/le04-einfbindings.md
      - 'Einführung CRUD': le04/le04-einfcrud.md
      - 'UE04-01': le04/ue04-01.md
      - 'UE04-02': le04/ue04-02.md
      - 'UE04-03': le04/ue04-03.md
      - 'UE04-04': le04/ue04-04.md
  - 'LE05-Docker-MySQL-Relationenmodell': 
      - le05/README.md
      - 'DOCKER-Installation MySQL-phpmyadmin': le05/instMySQL.md
      - 'UE05-01-MySQL und erste Datenbank': le05/ue05-01.md
      - 'UE05-02-Datentransfer von SQLite-DB nach MySQL': le05/ue05-02.md
      - 'UE05-03-Relationenmodell': le05/ue05-03.md
  - 'LE06-Normalformen': 
      - le06/README.md
      - 'UE06-01-Funktionale und Transitive Abhängigkeit': le06/ue06-01.md