site_name: WING - btw2201-Databases
site_url: https://tjaeggi.github.io/btw2201_databases/
theme:
  name: material
  font:
    text: Roboto
    #text: Red Hat
    code: Red Hat Mono
  logo:  assets/Micropython-logo.svg.png
  favicon: assets/Micropython-logo.svg.png
  #icon:
  #  logo: fontawesome/solid/face-smile-beam
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: deep orange
  features:
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate

plugins:
  - glightbox

extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/thomas-j%C3%A4ggi-026350141/

copyright: Copyright &copy; 2024 Thomas Jäggi

markdown_extensions:
  - attr_list
  - tables
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css


nav:
  - 'ABOUT THIS WEBSITE': 'index.md'
  - 'LE01-CSVs mit Python': 
      - 'UE01-1-Aufgaben': 'ue01-1.md' 
      - 'UE01-1-Lösungsvorschläge': 'Loesungsvorschlaege_ue01-1.md'
  - 'LE02-SELECT Abfragen': 
      - 'UE02-1-Aufgaben': 'UE02-1.md' 
      - 'UE02-1-Lösungsvorschläge': 'Loesungsvorschlaege_UE02-1.md'
      - 'UE02-2-Aufgaben und Lösungen': 'UE02-2.md'
  - 'LE03-Weiterführende SELECTs':
      - 'UE03-1-AB-Ranking Table und View': 'UE03-01-AB.md'
      - 'UE03-2-Datum und Zeit': 'UE03-2.md'
      - 'UE03-3-CSV in SQLite': 'UE03-3.md'
      - 'UE03-4-SQL-Abfragen Strasserverz.': 'UE03-4.md'
  - 'LE04-SQL und Python':
      - 'Einführung Python mit SQLite': 'LE04-EinfPythonSQLite.md'
      - 'Einführung Bindings': 'LE04-EinfBindings.md'
      - 'Einführung CRUD': 'LE04-EinfCRUD.md'
      - 'UE04-01': 'UE04-01.md'
      - 'UE04-02': 'UE04-02.md'
      - 'UE04-03': 'UE04-03.md'
      - 'UE04-04': 'UE04-04.md'


